version: "3"
services:
  db:
    image: mysql:5.6
    environment:
      MYSQL_DATABASE: root 
    ports:
      - "4306:3306"

  web:
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/Community
    ports:
      - "3000:3000"
    # appコンテナとdbコンテナを連携
    links:
      - db
